---
  - include_vars: ../vars/postgres_vars.yml
    tags: always

  - name: create postgres user
    user:
      name: "{{ postgresql_admin_user }}"
      state: present
    tags: always

  - name: create config directory
    file:
      name: "{{ pg_config_dir }}"
      state: directory
      owner: "{{ postgresql_admin_user }}"
      group: "{{ postgresql_admin_user }}"
    tags: always

  - name: upload file
    copy:
      src: ../files/pg_hba.conf
      dest: "{{ pg_config_dir }}"
    tags: upload

  # - include: show_status.yml
  #   tags: [showStatus,showAll]

  # - include: show_mode.yml
  #   tags: [showMode,showAll]
    
  # - include: show_repmgr.yml
  #   tags: [showRepmgr,showAll]

  - include: update_pghba.yml
    tags: updatePghba  
