--- # configure pg_hba.conf and restart Postgres services
- assert:
    that:
      - pg_database|default("") != ""
      - pg_user|default("") != ""
      - pg_address|default("") != ""
      - pg_entry_state|default("") != ""
      
- name: configure pg_hba.conf
  lineinfile:
    dest: "{{ pg_config_dir }}/pg_hba.conf"
    regexp: '^host\s+{{ pg_database }}\s+{{ pg_user }}\s+{{ pg_address }}\s+md5$'
    line: 'host   {{ pg_database }}   {{ pg_user }}   {{ pg_address }}    md5'
    state: "{{'present' if (pg_entry_state == 'add' or pg_entry_state == 'present') else 'absent' if (pg_entry_state == 'remove' or pg_entry_state == 'absent')}}"
    backup: yes
  register: pghba

- debug:
    msg: "pg_hba.conf file was updated. Attempting to restart postgresql..."
  when: pghba.changed
  
- name: touch a file to represent postgres service
  file:
    name: /tmp/postgresql.stat
    state: touch
  when: pghba.changed
