--- 

- hosts: ldap
  become: yes

  vars:
    env: othrd
    homedir: /Users/clark.wintersibm.com
    fwdir: "{{ homedir }}/CISAUTOMATION/ansible_framework/ansible_framework"
    envdir: "{{ homedir }}/CISAUTOMATION/ansible_deployment/InventoryDefinition/inventory/environments/{{ env }}"
    artifactdir: "{{ homedir }}/CISAUTOMATION/artifacts/Components"
    bindir: /lh_files/cis_assets
    ansdir: "/etc/ansible/{{ env }}"
    user: devops
    s3bucket: https://s3.amazonaws.com/clark-binaries
  
  tasks:
  - include: ../tasks/download_ldap_binaries.yml
    with_items:
      - sds
      - gskit
      - db2
      - db2-hadr
      - java
    tags: binaries 

  - include: ../tasks/get_artifacts.yml
    with_items:
      # - gskit
      # - db2-base
      # - sds-ldap
      - sds-ldap-commands
    tags: artifacts 
