--- # deploy code from the CISAUTOMATION repositories

- hosts: ldap
  become: yes

  vars:
    env: othrd
    homedir: /Users/clark.wintersibm.com
    fwdir: "{{ homedir }}/CISAUTOMATION/ansible_framework/ansible_framework"
    envdir: "{{ homedir }}/CISAUTOMATION/ansible_deployment/InventoryDefinition/inventory/environments/{{ env }}"
    bindir: /lh_files/cis_assets
    ansdir: "/etc/ansible/{{ env }}"
    user: devops
  
  tasks:
  - name: archive roles and playbooks
    become: no
    local_action: "shell cd {{ fwdir }}; /usr/bin/tar -czvf {{ item }}.tar.gz {{ item }}"
    with_items:
      - roles
      - playbooks

  - name: "archive {{ env }} inventory"
    become: no
    local_action: "shell cd {{ envdir }}; /usr/local/bin/gtar --transform \"s/^./inventory/\" -czvf {{ fwdir }}/inventory.tar.gz ."

  - include: ../tasks/get_cisautomation.yml
    with_items:
      - roles
      - playbooks
      - inventory
