--- # configuring lab server users and directory structure

- hosts: rhel-lab
  become: yes
  tasks:
  # - user:
  #     name: test
  #     password: test123
  #     shell: /bin/bash
  #     #generate_ssh_key: yes

  # - file:
  #     name: /home/test/playbooks
  #     state: directory
  #     owner: test
  #     group: test
  #     mode: 0755

  - name: install EPEL-RELEASE repo for EL7
    yum_repository:
      name: epel-release
      description: Extra Packages for Enterprise Linux
      state: present
      enabled: yes
      baseurl: https://dl.fedoraproject.org/pub/epel/7/x86_64/

  - name: update all packages
    yum:
      name: '*'
      state: latest

  - name: install packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - ansible
      - git
      - python
      - python-devel
      - python-pip

  - name: add user
    user:
      name: ansible
      state: present
  