--- # configuring lab server users and directory structure

- hosts: rhel-lab
  become: yes
  tasks:
  # - user:
  #     name: test
  #     password: test123
  #     shell: /bin/bash
  #     #generate_ssh_key: yes

  # - file:
  #     name: /home/test/playbooks
  #     state: directory
  #     owner: test
  #     group: test
  #     mode: 0755

  - name: install EPEL-RELEASE repo 
    yum_repository:
      name: epel-release
      description: Extra Packages for Enterprise Linux
      state: present
      enabled: yes
      baseurl: https://dl.fedoraproject.org/pub/epel/7/x86_64/

  - yum:
      name: '*'
      state: latest

  - yum:
      name: ansible
      state: latest
  