--- # start EC2 instances depending on tags passed at execution time

- hosts: local
  vars:
    ldapinstid: i-0846dada88ffcbe03
    ansctlinstid: i-0c5773867164538d4
    region: us-east-1
  tasks:
  - name: start LDAP sandbox EC2 instance
    ec2:
      instance_ids: "{{ ldapinstid }}"
      state: running
      region: "{{ region }}"
    tags: ldap 

  - name: start Ansible Control EC2 instance
    ec2:
      instance_ids: "{{ ansctlinstid }}"
      state: running
      region: "{{ region }}"
    tags: ansctl
