- name: check currently installed version 
  shell: "{{ was_install_dir }}/bin/versionInfo.sh | grep -A1 'IBM WebSphere Application Server' | tail -n 1 | awk '{print $2}' | sed 's/\\./0/3'"
  register: installed_fixpack

- name: check installed_fixpack string
  debug: 
    msg: "{{ installed_fixpack.stdout }}"

- name: check fixpack_version string
  debug: 
    msg: "{{ fixpack_version }}"

- name: quit if fixpack is already installed
  fail:
    msg: "Fixpack already installed"
  when: "{{ installed_fixpack.stdout >= fixpack_version }}"

- name: touch a file based on fixpack version
  file:
    name: "/tmp/WAS_{{ fixpack_version }}"
    state: touch
