- name: check currently installed version 
  shell: '{{ was_install_dir }}/bin/versionInfo.sh | grep -A1 "IBM WebSphere Application Server" | tail -n 1 | awk "{print $2}" | sed "s/\./0/3"'
  register: installed_fixpack

- name: touch a file based on whether fixpack version is the same
  file:
    name: "/tmp/WAS_{{ fixpack_version }}"
    state: touch
  when: "{{ installed_fixpack.stdout != fixpack_version }}"
